platform :ios, '7.0'

pod 'MKNetworkKit'
pod "MagicalRecord/Shorthand"
pod 'iRate', '~> 1.10.2'
pod 'iVersion'
pod 'Google-Mobile-Ads-SDK'
pod 'ActionSheetPicker-3.0'
pod 'MKNetworkKit'
pod 'Parse'
pod 'ParseFacebookUtils'
pod 'ParseCrashReporting'
pod 'ParseUI'
pod 'MBProgressHUD'
pod 'Reachability'
pod 'FormatterKit'
pod 'UIImageEffects'
pod 'AFNetworking', '~> 2.5'
pod 'ICDMaterialActivityIndicatorView', '0.0.2'
pod 'JBChartView'
