# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
target 'ExecutiveDashboard' do

  pod 'PNChartSwift', :path => "../"
  pod 'MagicalRecord'
  pod 'AFNetworking', '~> 2.5'
  pod 'MBProgressHUD'
  pod 'MaterialKit'

end



